### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by sochartgit** [SpiderLabs/HostHunter#6]
I've followed the instructions. Hosthunter works until I try to enable de screen capture and bing options.
I get this error:

Traceback (most recent call last):
  File "/home/kali/HostHunter/hosthunter.py", line 467, in <module>
    driver = webdriver.Chrome(executable_path=DRIVER, options=chrome_opt)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by piratetm** [comment]
I have the same problem. I can't find a solution...

**Comment by dayojohn19** [comment]
someone ??

**Comment by dayojohn19** [comment]
same here

**Comment by superhedgy** [comment]
I've updated the code and also included the chromdrivers.  Please try again.
